language: python
python:
  - "2.7"
# command to install dependencies
sudo: required

install:
  - pip install PySide
  # Qt4
  - sudo apt-get install -y libqt4-dev
  # PyQt4
  - tar xzf /downloads/pyqt4.tar.gz --keep-newer-files
  - pushd PyQt-x11-gpl-4.11.3
  - python configure.py -c --confirm-license --no-designer-plugin -e QtCore -e QtGui
  - make
  - sudo make install
  - popd
  
addons:
  apt:
    sources:
    - aircrack-ng
